// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetWebApi.Context;

#nullable disable

namespace VetWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221209204739_BuildBd")]
    partial class BuildBd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VetWebApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<string>("Comorbidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrequenciaCardiaca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrequenciaRespiratoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hematocrito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leucocitos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PressaoArterialSistemica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalId");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("VetWebApi.Models.Remedio", b =>
                {
                    b.Property<int>("RemedioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RemedioId"));

                    b.Property<string>("EfeitoAdverso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MecanismoAcao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PodeAumentarFrequenciaCardiaca")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeAumentarFrequenciaRespiratoria")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeAumentarHematocritos")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeAumentarLeucocitos")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeAumentarPressaoArterial")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeDiminuirFrequenciaCardiaca")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeDiminuirFrequenciaRespiratoria")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeDiminuirHematocritos")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeDiminuirLeucocitos")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeDiminuirPressaoArterial")
                        .HasColumnType("bit");

                    b.Property<string>("PrincipioAtivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViaAdministracao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RemedioId");

                    b.ToTable("Remedios");
                });
#pragma warning restore 612, 618
        }
    }
}
